apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-frontend
  template:
    metadata:
      labels:
        app: task-frontend
    spec:
      containers:
        - name: task-frontend
          image: quoc01973/task-frontend:latest  
          ports:
            - containerPort: 3000  
          env:
            - name: VITE_BACKEND_URL
              value: "http://task-backend:8080"  
---
apiVersion: v1
kind: Service
metadata:
  name: task-frontend
spec:
  selector:
    app: task-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  
